### ISSUE TITLE
Add DESCRIPTION so install from github works

### ISSUE THREAD

**Issue by AMChalkie** [RussBainer/gCrisprTools#15]
Hi,

I know you would prefer me using the dev package, but... would be nice to be able to do directly from here.

library(githubinstall)
R.3.4.4.>githubinstall("gCrisprTools")
Suggestion:
 - OscarBrock/gCrisprTools  An R/Bioconductor package for the integrated analysis of pooled high-throughput CRISPR/Cas9 or shRNA screening experiments.
Do you want to install the package (Y/n)?  
Installing "gCrisprTools" package from GitHub, but already installed from unknown repository.
This package is already installed. Are you sure you want to overwrite it (Y/n)?  Y
Downloading GitHub repo OscarBrock/gCrisprTools@master
from URL https://api.github.com/repos/OscarBrock/gCrisprTools/zipball/master
Installation failed: Does not appear to be an R package (no DESCRIPTION)

**Comment by OscarBrock** [comment]
Hi Alistair,

I'm sorry but syncing the current build from Bioc is kind of a bear- I honestly didn't realize that this repo wasn't syncing with the official release, and I am trying to figure out how to get them to the same place (this repo is quite a ways behind the BioC one). 

I'm working on fixing this, but it will take a sec before I can get everything ready on github; sorry for the inconvenience.

**Comment by AMChalkie** [comment]
No worries at all. I appreciate the code and will let you know if I have any more suggestions or find any inconsistencies.

**Comment by OscarBrock** [comment]
Try now. I am still getting errors on my end of the git client, but it appears as though the master branch has what it needs; let me know if it fails. 

-R

**Comment by AMChalkie** [comment]
Not quite yet. 
Downloading GitHub repo OscarBrock/gCrisprTools@master
from URL https://api.github.com/repos/OscarBrock/gCrisprTools/zipball/master
Installing gCrisprTools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1b/n55kx5h92sjb545dh4t79x1m5fmmpb/T/Rtmpi9ZJ74/devtools303c2fafe6f3/OscarBrock-gCrisprTools-faabbd5' --library='/Users/achalk/Library/R/3.4/library' --install-tests 

* installing *source* package ‘gCrisprTools’ ...
** R
** data
** inst
** tests
** preparing package for lazy loading
Error in parse(nsFile, keep.source = FALSE, srcfile = NULL) : 
  13:1: unexpected input
12: export(ct.alphaBeta)
13: <<
    ^
ERROR: lazy loading failed for package ‘gCrisprTools’
* removing ‘/Users/achalk/Library/R/3.4/library/gCrisprTools’
* restoring previous ‘/Users/achalk/Library/R/3.4/library/gCrisprTools’
Installation failed: Command failed (1)

**Comment by OscarBrock** [comment]
Still some artifacts in the NAMESPACE file. Try now?

**Comment by AMChalkie** [comment]
Not quite there...

Downloading GitHub repo OscarBrock/gCrisprTools@master
from URL https://api.github.com/repos/OscarBrock/gCrisprTools/zipball/master
Installing gCrisprTools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1b/n55kx5h92sjb545dh4t79x1m5fmmpb/T/Rtmp8Q0k1Y/devtools30c64b7d2c77/OscarBrock-gCrisprTools-1eea276' --library='/Users/achalk/Library/R/3.4/library' --install-tests 

* installing *source* package ‘gCrisprTools’ ...
** R
** data
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
Warning in file(con, "w") :
  cannot open file '/Users/achalk/Library/R/3.4/library/gCrisprTools/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed
* removing ‘/Users/achalk/Library/R/3.4/library/gCrisprTools’
* restoring previous ‘/Users/achalk/Library/R/3.4/library/gCrisprTools’
Installation failed: Command failed (1)

**Comment by OscarBrock** [comment]
Weird- it installs fine on my end, but it looks like some of the vignette dependencies needed cleanup.

Try now.
