### ISSUE TITLE
alignment statistics ct.makeQCReport

### ISSUE THREAD

**Issue by AMChalkie** [RussBainer/gCrisprTools#16]
From https://www.bioconductor.org/packages/devel/bioc/vignettes/gCrisprTools/inst/doc/gCrisprTools_Vignette.html

Code for best practise generation of the aln object would be helpful, commenting on what script/tool usually generates the source matrix.

may => must (in documentation)

2.5 Alignment Statistics Users may provide a matrix of alignment statistics to enhance some applications, including QC reporting. These should be provided as a numeric matrix in which rows correspond to targets (reads containing a target cassette), nomatch (reads containing a cassette sequence but not a known target sequence), rejections (reads not containg a cassette sequence), and double_match (reads derived from multiple cassettes). The column names should exactly match the colnames() of the ExpressionSet object. Simple charting functionality is also provided to inspect the alignment rates of each sample. 

ct.makeQCReport(es, 
                             trim = 1000, 
                             log2.ratio = 0.05, 
                             sampleKey = sk, 
                             annotation = ann, 
                             #                 aln = aln, 
                             identifier = 'Crispr_QC_Report',
                             lib.size = NULL,
                             outdir = file_path_report
  )      

Error in ct.makeQCReport(es, trim = 1000, log2.ratio = 0.05, sampleKey = sk,  : 
  argument "aln" is missing, with no default

**Comment by RussBainer** [comment]
This has been fixed in the move to 2.0
