### ISSUE TITLE
ct.normalizeMedians() functions has a bug

### ISSUE THREAD

**Issue by rkostadi** [RussBainer/gCrisprTools#24]
Hi,

In the below example, I am making a small dataset, and showing the median normalization in the ct.normalizeMedians() code versus the ~correct formula (from limma's https://rdrr.io/bioc/limma/src/R/norm.R ). In the corrected formula, the summary shows that the medians for the three groups are the same post-normalization, whereas the medians after ct.normalizeMedians() are different. Do you think this is correct?

```
g1 <- data.frame(sample.id="g1",guide.id=1:1000,counts=rnorm(1000,mean=9,sd=1))
g2 <- data.frame(sample.id="g2",guide.id=1:1000,counts=rnorm(1000,mean=10,sd=1))
g3 <- data.frame(sample.id="g3",guide.id=1:1000,counts=rnorm(1000,mean=11,sd=2))
df <- rbind(g1,g2,g3)


counts <- pivot_wider(df,names_from=sample.id,values_from=counts)
counts <- counts[,-1]
lib.size <- colSums(counts)  
y <- t(log2(t(counts + 0.5)/(lib.size + 1) * 1e+06))
  cmed <- apply(y, 2, median, na.rm = TRUE)
  cmed <- cmed - mean(cmed)
  correctedCounts <- 2^t(t(y) - cmed)
correctedCounts1 <- (t(t(correctedCounts) * ((lib.size + 1) / 1e+06)) - 0.5)

normalizeMedianValues <- function(x) 
{
narrays <- NCOL(x)
if(narrays==1) return(x)
cmed <- log(apply(x, 2, median, na.rm=TRUE))
cmed <- exp(cmed - mean(cmed))
t(t(x)/cmed)
}
gs.counts <- normalizeMedianValues(counts)
## compare
summary(counts)
summary(gs.counts)
summary(correctedCounts1)
```

Thanks,
Rumen

**Comment by RussBainer** [comment]
Hi Rumen, thanks for the comment. 

The difference you observe is a consequence of the `lib.size` argument, which as you probably know is meant to accommodate upstream correction related to differences in sequencing depth across libraries. This is not available in the limma method, which I believe already assumes that the expression values have been corrected for sequencing depth. 

That said, I appreciate your intuition about the meaning of a "median normalization", and I agree that in the absence of such an explicit correction, the function should correct to the standard medians. I'll update the code to deal with that edge case.

**Comment by rkostadi** [comment]
Thank you, Russell.
